{% set name = "dnslib" %}
{% set version = "0.9.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21769b01158fe70be89121754349f2835dccdf21d5c011cec9fa28a48fa555d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - dnslib

about:
  home: http://bitbucket.org/paulc/dnslib/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple library to encode/decode DNS wire-format packets
  doc_url: https://pypi.org/project/dnslib/
  dev_url: https://bitbucket.org/paulc/dnslib/src/default/

extra:
  recipe-maintainers:
    - mwilson8
    - mxr-conda
