travis:
  secure:
    BINSTAR_TOKEN: kUollE5raQoCA6Pgmsm1oODXWKUXOZPZF/cdFbXieQ8FRx5mi2LLhOP2DRO/KLiOQlTwPHD7nfyDN8Fs+RkM/euqcB4C1BsExBWuNc9cc3ALscYpzS9edFhGrBGnYOgqoh/3pRdlqRGVV0bSTY29f9jePe29IjQSPYARKqQNLWX2+mup/OIZjw/Anb/VVBnriWDU6yCahi7HL4TjGyB3i8VFxnW96Jle5vlH7kr5rd+UVtmexcZ3bcieLplZ3zRwIIuMttUNm9oakQ+1MrpYhVbKvt54I/Ewmol1rxVKScVWxmu61l+F+3IG59Ww7JOlaGB6A2ufNb769bG64HbbC7Cy6KjwHT/12OH5aHUcDssy80DhtAyNVKkkRN0kiwDdJ67ksARHlN9DNexkyHCGU92F7Tzbj8D2PT+YN70/0nJ7aWP/Us3m0gPyIF74hQrrXlhH8tcPppqrYoiaQ63UEf1WBdyZXprLgIuG3eDU1sQ3DC5QB58pB16jDeckcF6D0JgzwNYbcmXRJEuAHf3CnFoUjQUVyDeIXgACWgUa5aGn8nSB00JkRqvnJ9kPW4+KZEDYEbYvSCuh6W7AqHq7bRs2NDkrsi5nzdiph3xT8u1AOvaWylZ0IndedXJGi8kxVc12NYKUxhSNvQyhsQvEH7PXzQwf9qGk69EV5rQtccQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
